---
# tasks file for mariadb

- name: Add mariadb repository key
  apt_key:
    id: '0xcbcb082a1bb943db'
    keyserver: keyserver.ubuntu.com
    state: present
  register: mariadb_apt_key
  tags:
    - setup
    - mariadb

- name: Update keyring
  when: mariadb_apt_key.changed
  command: "apt-key update"
  tags:
    - setup
    - mariadb
    - skip_ansible_lint

- name: Add mariadb repository
  apt_repository:
    repo: "{{ mysql_apt_repo }}"
    update_cache: true
    state: present
  tags:
    - setup
    - mariadb

- name: Install mariadb requirements
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mysql_packages }}"
    - "{{ mysql_additional_packages }}"
  tags:
    - package
    - mariadb

- name: Copy mariadb config
  when: mysql_config_files is defined
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ mysql_config_files }}"
  notify: restart mysql
  tags:
    - config
    - mariadb

- name: Add mysql to ssl-cert group
  when: mysql_ssl_key is defined
  user:
    name: mysql
    append: true
    groups: ssl-cert
  tags:
    - setup
    - mariadb

- name: Start and enable mariadb
  service:
    name: mysql
    state: started
    enabled: true
  tags:
    - service
    - mariadb

- name: Securing root user with password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password | mandatory }}"
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: true
    state: present
  tags:
    - setup
    - mariadb

- name: Create password-file with root password credentials
  blockinfile:
    dest: "/root/.my.cnf"
    create: true
    block: |
      [client]
      user=root
      password={{ mysql_root_password }}
  tags:
    - setup
    - mariadb

- name: Restrict root login to localhost and mysql_address
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: true
    state: present
  with_items:
    - "127.0.0.1"
    - "{{ mysql_address }}"
  tags:
    - setup
    - mariadb

- name: Deleting all logins from other hosts
  when: item != "localhost"
  mysql_user:
    name: root
    host: "{{ item }}"
    state: absent
    check_implicit_admin: true
  with_items:
    - "::1"
    - "{{ ansible_hostname }}"
    - "{{ ansible_fqdn }}"
  tags:
    - setup
    - mariadb

- name: Remove anonymous users
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
    check_implicit_admin: true
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
  tags:
    - setup
    - mariadb

- name: Remove test database
  mysql_db:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ mysql_remove_databases }}"
    - test
  notify: restart mysql
  tags:
    - setup
    - mariadb

- name: Create databases
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
  with_items:
    - "{{ mysql_create_databases }}"
  tags:
    - setup
    - mariadb

- name: Transfer Schema to database
  template:
    src: "{{ item }}"
    dest: "/var/tmp/{{ item | basename | replace('.j2', '') }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ mysql_schema_files }}"
  register: mysql_db_schema_update
  tags:
    - schema
    - setup
    - mariadb

- name: Import Schema
  when: item.changed
  mysql_db:
    state: import
    name: smtp
    target: "{{ item.dest }}"
    config_file: /root/.my.cnf
  with_items:
    - "{{ mysql_db_schema_update.results }}"
  tags:
    - schema
    - setup
    - mariadb
    - skip_ansible_lint
